#!/bin/bash
# splitroute-pac.sh — PAC (Proxy Auto-Config) generation and server control.
#
# Sourced by splitroute-watch.sh. Not executable on its own.
# Depends on variables set by load_config() in splitroute-lib.sh:
#   DOMAINS, ROUTE_IPS, PAC_PORT, UPSTREAM_PROXY
# And path constants:
#   SPLITROUTE_PAC_DIR, SPLITROUTE_PAC_FILE, SPLITROUTE_PAC_PID, SPLITROUTE_LOG

# Regenerate ~/.splitroute/pac/proxy.pac from the currently loaded config.
# Returns 0 on success, 1 on error. Safe to call repeatedly.
pac_rewrite() {
    mkdir -p "$SPLITROUTE_PAC_DIR"
    local upstream tmp pair base mask d cidr
    upstream=$(detect_upstream_proxy 2>/dev/null || true)
    tmp="$SPLITROUTE_PAC_FILE.tmp"

    {
        echo "// Auto-generated by splitroute. Do not edit."
        echo "// Source: $SPLITROUTE_CONF"
        echo "function FindProxyForURL(url, host) {"
        echo '  host = host.toLowerCase();'

        # Domain rules (shExpMatch)
        if [ ${#DOMAINS[@]} -gt 0 ]; then
            for d in "${DOMAINS[@]}"; do
                # Strip quotes that could break the JS string
                d="${d//\"/}"
                echo "  if (shExpMatch(host, \"$d\")) return \"DIRECT\";"
            done
        fi

        # IP/CIDR rules (isInNet)
        if [ ${#ROUTE_IPS[@]} -gt 0 ]; then
            echo '  if (/^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/.test(host)) {'
            for cidr in "${ROUTE_IPS[@]}"; do
                if ! pair=$(cidr_to_netmask "$cidr" 2>/dev/null); then
                    continue
                fi
                base="${pair% *}"
                mask="${pair#* }"
                echo "    if (isInNet(host, \"$base\", \"$mask\")) return \"DIRECT\";"
            done
            echo "  }"
        fi

        if [ -n "$upstream" ]; then
            echo "  return \"PROXY $upstream; DIRECT\";"
        else
            echo "  return \"DIRECT\";"
        fi
        echo "}"
    } > "$tmp" || return 1

    mv -f "$tmp" "$SPLITROUTE_PAC_FILE"
    chmod 644 "$SPLITROUTE_PAC_FILE" 2>/dev/null || true
}

# Is the recorded PAC server process alive?
pac_is_running() {
    local pid
    [ -f "$SPLITROUTE_PAC_PID" ] || return 1
    pid=$(cat "$SPLITROUTE_PAC_PID" 2>/dev/null)
    [ -n "$pid" ] || return 1
    kill -0 "$pid" 2>/dev/null
}

# Start the PAC HTTP server if not already running.
# Uses /usr/bin/python3 (ships with macOS developer tools since 10.15).
# Binds to 127.0.0.1 only.
pac_start() {
    if pac_is_running; then
        return 0
    fi
    # Port sanity: reject if something else is already on the port.
    if nc -z -G 1 127.0.0.1 "${PAC_PORT:-7899}" 2>/dev/null; then
        echo "$(log_ts): pac_start: port ${PAC_PORT:-7899} already in use, not starting" >> "$SPLITROUTE_LOG"
        return 1
    fi
    mkdir -p "$SPLITROUTE_PAC_DIR"
    # Ensure the PAC file exists before first request.
    [ -f "$SPLITROUTE_PAC_FILE" ] || pac_rewrite
    local py
    py=$(command -v python3 || true)
    if [ -z "$py" ]; then
        echo "$(log_ts): pac_start: python3 not found; PAC server not started" >> "$SPLITROUTE_LOG"
        return 1
    fi
    # nohup + setsid-like disown so the server survives the sourcing shell exit
    # via launchd restarts is irrelevant — watch keeps us alive.
    nohup "$py" -u -m http.server "${PAC_PORT:-7899}" \
        --bind 127.0.0.1 \
        --directory "$SPLITROUTE_PAC_DIR" \
        >/dev/null 2>&1 &
    local pid=$!
    disown "$pid" 2>/dev/null || true
    echo "$pid" > "$SPLITROUTE_PAC_PID"
    echo "$(log_ts): pac_start: pid=$pid port=${PAC_PORT:-7899}" >> "$SPLITROUTE_LOG"
    # Give the server a moment before anyone queries it.
    sleep 0.3
    return 0
}

# Stop the PAC HTTP server if we have a recorded PID.
pac_stop() {
    local pid
    if [ -f "$SPLITROUTE_PAC_PID" ]; then
        pid=$(cat "$SPLITROUTE_PAC_PID" 2>/dev/null)
        if [ -n "$pid" ] && kill -0 "$pid" 2>/dev/null; then
            kill "$pid" 2>/dev/null || true
            # Give it up to 2s to exit, then force
            local i=0
            while kill -0 "$pid" 2>/dev/null; do
                i=$((i + 1))
                [ "$i" -ge 10 ] && break
                sleep 0.2
            done
            if kill -0 "$pid" 2>/dev/null; then
                kill -9 "$pid" 2>/dev/null || true
            fi
            echo "$(log_ts): pac_stop: pid=$pid" >> "$SPLITROUTE_LOG"
        fi
        rm -f "$SPLITROUTE_PAC_PID"
    fi
}

# Rewrite PAC and ensure the server is running. Idempotent.
pac_apply() {
    pac_rewrite || return 1
    pac_start
}
