#!/usr/bin/env bats
# Tests for splitroute-pac.sh PAC content generation.

load test_helper

setup() {
    _sandbox_setup
    # shellcheck source=/dev/null
    source "$SPLITROUTE_DIR/splitroute-lib.sh"
    # shellcheck source=/dev/null
    source "$SPLITROUTE_DIR/splitroute-pac.sh"
    SPLITROUTE_PAC_DIR="$SPLITROUTE_DIR/pac"
    SPLITROUTE_PAC_FILE="$SPLITROUTE_PAC_DIR/proxy.pac"
    mkdir -p "$SPLITROUTE_PAC_DIR"
}

@test "pac_rewrite emits DIRECT for *.pattern" {
    write_conf <<'EOF'
domain: *.example.com
EOF
    load_config "$SPLITROUTE_CONF"
    pac_rewrite
    grep -q 'shExpMatch(host, "\*\.example\.com")' "$SPLITROUTE_PAC_FILE"
    grep -q 'return "DIRECT"' "$SPLITROUTE_PAC_FILE"
}

@test "pac_rewrite emits DIRECT for bare hostnames" {
    write_conf <<'EOF'
host: git.example.com
host: bastion.example.com
EOF
    load_config "$SPLITROUTE_CONF"
    pac_rewrite
    grep -q 'shExpMatch(host, "git.example.com")' "$SPLITROUTE_PAC_FILE"
    grep -q 'shExpMatch(host, "bastion.example.com")' "$SPLITROUTE_PAC_FILE"
}

@test "pac_rewrite emits isInNet for IP/CIDR routes" {
    write_conf <<'EOF'
10.0.0.0/8
192.168.5.5
EOF
    load_config "$SPLITROUTE_CONF"
    pac_rewrite
    grep -q 'isInNet(host, "10.0.0.0", "255.0.0.0")' "$SPLITROUTE_PAC_FILE"
    grep -q 'isInNet(host, "192.168.5.5", "255.255.255.255")' "$SPLITROUTE_PAC_FILE"
}

@test "pac_rewrite emits isInNet for PAC-only domain IPs" {
    write_conf <<'EOF'
domain: 10.0.99.0/24
EOF
    load_config "$SPLITROUTE_CONF"
    pac_rewrite
    grep -q 'isInNet(host, "10.0.99.0", "255.255.255.0")' "$SPLITROUTE_PAC_FILE"
}

@test "pac_rewrite is host case-insensitive (lowercases incoming host)" {
    write_conf <<'EOF'
host: git.example.com
EOF
    load_config "$SPLITROUTE_CONF"
    pac_rewrite
    grep -q 'host = host.toLowerCase()' "$SPLITROUTE_PAC_FILE"
}

@test "pac_rewrite emits DIRECT fallback when no upstream proxy detected" {
    # detect_upstream_proxy probes 7890/7897/6152 — unlikely to be listening
    # in a CI sandbox. Confirm fallback is DIRECT (not PROXY).
    detect_upstream_proxy() { return 1; }
    write_conf <<'EOF'
host: git.example.com
EOF
    load_config "$SPLITROUTE_CONF"
    pac_rewrite
    # Last meaningful return statement should be plain DIRECT
    grep -q 'return "DIRECT";' "$SPLITROUTE_PAC_FILE"
}

@test "pac_rewrite produces valid JS function structure" {
    write_conf <<'EOF'
host: git.example.com
EOF
    load_config "$SPLITROUTE_CONF"
    pac_rewrite
    # Header
    head -1 "$SPLITROUTE_PAC_FILE" | grep -q "Auto-generated by splitroute"
    # Function signature
    grep -q "function FindProxyForURL(url, host)" "$SPLITROUTE_PAC_FILE"
    # Closes properly
    tail -1 "$SPLITROUTE_PAC_FILE" | grep -q "}"
}
